### PR TITLE
added section_for, article_for, and span_for helpers

### PR DESCRIPTION
**Pull request by beaugaines**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but I consider this gem a deprecation gem and I don't want to add new features to it.

**Comment by brendon** [comment]
Hi @rafaelfranca, I was trying to hunt down the conversation that led to this feature being removed to a gem, and its overall use deprecated. Is there a better way to do this other than just string interpolation?

**Comment by rafaelfranca** [comment]
I don't get your question. What are you trying to do what is using string interpolation?

**Comment by brendon** [comment]
Sorry, I'm just asking if there is a record of the rationale for removing this from Rails, and (other than using this gem) what should users be doing going forward instead of content_tag_for? I only ask this because of your comment above about not wanting to extend the features of the gem. That would indicate to me that you'd rather people not use this feature in projects going forward?

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/issues/18337

All this gem does is add a id and class depending in the ID of the record. You can easily do this using the `dom_id` method. But I don't remember the last time that I needed to use this helper in an application, so the main reason to remove is that it is not so useful for the majority of applications.

**Comment by brendon** [comment]
Thanks @rafaelfranca :) That's what I was looking for. I came across my developer doing this manually with string interpolation `"user_#{user.id}"` so I remembered this feature and told him to use it. I'll just tell him about `dom_id` instead. I notice the deprecation warning refers users to the Rails upgrade guide for more information. I couldn't find anything in the guide, so perhaps this is pending (or I was looking in the wrong place), but when it's done, I think it'd be helpful for people to know that `dom_id` is recommended instead. Thanks again :)

**Pull request closed without merging**
